version: "3.7"

services:
  muskbot:
    build: "."
    env_file:
      - ".env"
    restart: "always"
    volumes:
      - "./google_client_secrets.json:/google_client_secrets.json"
      - "./bot:/app/bot"
